#-----------------------------------------------------------------------
# IDL lib (if any) and binaries
#-----------------------------------------------------------------------

# Name of the library we will create

LIBSO_PREFIX = libGcpIdl

IDL = true

# And include the generic Makefile

include $(GCPTOP)/Makefile_generic

