#ifndef GCP_ANTENNA_CONTROL_EMLDEBUG_H
#define GCP_ANTENNA_CONTROL_EMLDEBUG_H

//#define EML_DEBUG
//#define EML_PX_DEBUG
//#define EML_PORT_DEBUG
//#define EML_TRACKER_DEBUG

#endif // End #ifndef GCP_ANTENNA_CONTROL_EMLDEBUG_H
