#!/bin/tcsh
$GCP_DIR/bin/sptUMediator ctlhost=localhost deicinghost=deicing deicingport=5207 ptelhost=pointingTel ptelport=5207 logd=$GCP_DIR/runlogs logf=sptUMediator debuglevel=0 hwhost=stoli2 diohost=stoli2





