#ifndef GCP_UTIL_COMMON_DIRECTIVES_H
#define GCP_UTIL_COMMON_DIRECTIVES_H

#define DIR_IS_STABLE  (IS_STABLE)
#define DIR_DEBUG      (COMPILE_WITH_DEBUG)
#define DIR_HAVE_USB   (HAVE_USB)

#define DIR_HAVE_RT    (HAVE_RT)

#define DIR_IS_GCP     (IS_GCP) 
#define DIR_IS_BICEP   (IS_BICEP) 
#define DIR_IS_SPT     (IS_SPT) 
#define DIR_IS_QUIET   (IS_QUIET) 
#define DIR_IS_EXPSTUB (IS_EXPSTUB) 

#endif // End #ifndef GCP_UTIL_COMMON_DIRECTIVES_H
