#!/bin/sh
module="tfp"
device="tfp"
mode="664"

# invoke insmod with all arguments we were passed
# and use a pathname, as newer modutils don't look in . by default
/sbin/rmmod $module

# remove stale nodes
rm -f /dev/${device}0
